steps:
  - id: "Rodando Teste da aplicação"
    name: "gcr.io/cloud-builders/go"
    args: ["test", "./src/sqrt"]
    env: ["GOPATH=."]

  - id: "Compilando Golang"
    name: "gcr.io/cloud-builders/go"
    args: ["build", "-o", "./src/sqrt", "./src/sqrt"]
    env: ["GOPATH=."]

  - id: "Montando Imagem Docker"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/desafio-deploy-continuo:$SHORT_SHA",
        ".",
      ]

  - id: "Pushing Image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/desafio-deploy-continuo:$SHORT_SHA"]

  - id: "Adjusting deployment file - k8s"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        sed "s#img-app-deployment#gcr.io/$PROJECT_ID/desafio-deploy-continuo:$SHORT_SHA#g" k8s/app/deployment.yaml > k8s/app/deployment-new.yaml;
        cat k8s/app/deployment-new.yaml

  - id: "Deploying k8s"
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "k8s/app/deployment-new.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=code-education-cluster"
